# Generated by Django 5.1.6 on 2025-03-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255, null=True, verbose_name='app')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
