# Generated by Django 5.1.6 on 2025-03-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='app',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='app'),
        ),
    ]
