# Generated by Django 5.1.6 on 2025-03-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255, null=True, verbose_name='user')),
                ('path', models.TextField(verbose_name='path')),
                ('body', models.TextField(verbose_name='body')),
                ('method', models.CharField(max_length=8, verbose_name='method')),
                ('ip_address', models.GenericIPAddressField(verbose_name='ip_address')),
                ('user_agent', models.TextField(verbose_name='user_agent')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('country_name', models.CharField(max_length=255, null=True, verbose_name='country_name')),
                ('process_time_ms', models.FloatField(verbose_name='process_time_ms')),
                ('status_code', models.IntegerField(verbose_name='status_code')),
                ('error_message', models.TextField(null=True, verbose_name='error_message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
